name: merge

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: |
        cd github-actions-merge
        pip install pipenv
        pipenv sync
        pipenv run python3 github-actions-merge/helloworld.py

    - name: Send message to Slack API
      uses: archive/github-actions-slack@master
      with:
        slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
        slack-channel: build_result
        slack-text: Hello! Event "${{ github.event_name }}" in "${{ github.repository }}" 🤓

    - name: Result from "Send Message"
      run: echo "The result was ${{ steps.notify.outputs.slack-result }}"
