# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions

name: test schedule

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '*/15 * * * *'
jobs:
  build:
    name: schedule helloworld
    runs-on: ubuntu-latest
    steps:
      - name: Echo the greeting's time
        run: hostname
