name: merge

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install python
      run: sudo apt-get install -y python3 python3-dev python3-pip setuptools

    - name: install requirement.txt
      run: |
        cd github-actions-merge
        pip3 install -r requirements.txt
    - name: run test
      run: |
        cd github-actions-merge
        python3 helloworld.py

    - name: Send message to Slack API
      uses: archive/github-actions-slack@master
      with:
        slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
        slack-channel: build_result
        slack-text: Hello! Event "${{ github.event_name }}" in "${{ github.repository }}" 🤓

    - name: Result from "Send Message"
      run: echo "The result was ${{ steps.notify.outputs.slack-result }}"
